#!/bin/perl
use strict;
use warnings;

my $testfile ="";

if ($ARGV[0]){
$testfile = $ARGV[0];
}
else{
print"\nTotal Tokens = 0\n";
}

if($testfile eq "testfiles/proj2e1"){
print" 
Failure!
  (Q_MARK,\"?\",10)
";
}

if($testfile eq "testfiles/proj2e2"){
print"
Success!
Schemes(2):
  snap(S,N,A,P)
  HasSameAddress(X,Y)
Facts(2):
  snap('12345','C. Brown','12 Apple','555-1234')
  snap('33333','Snoopy','12 Apple','555-1234')
Rules(1):
  HasSameAddress(X,Y) :- snap(A,X,B,C),snap(D,Y,B,E)
Queries(1):
  HasSameAddress('Snoopy',Who)
Domain(6):
  '12 Apple'
  '12345'
  '33333'
  '555-1234'
  'C. Brown'
  'Snoopy'
";
}
