#!/bin/perl
use strict;
use warnings;

my $testfile ="";

if ($ARGV[0]){
$testfile = $ARGV[0];
}
else{
print"\nTotal Tokens = 0\n";
}

if($testfile eq "testfiles/proj4e1"){
print" 
SK(A,'c')? Yes(2)
  A='a'
  A='b'
SK('b','c')? Yes(1)
SK(X,X)? Yes(1)
  X='b'
SK(A,B)? Yes(3)
  A='a', B='c'
  A='b', B='b'
  A='b', B='c'
";
}

if($testfile eq "testfiles/proj4e2"){
print"
ab('joe','jim')? Yes(1)
ab(who,'bob')? Yes(3)
  who='bob'
  who='jim'
  who='joe'
ab('joe',anyone)? Yes(2)
  anyone='bob'
  anyone='jim'
ab(X,X)? Yes(1)
  X='bob'
ab(X,Y)? Yes(4)
  X='bob', Y='bob'
  X='jim', Y='bob'
  X='joe', Y='bob'
  X='joe', Y='jim'
";
}
if($testfile eq "testfiles/proj4e3"){
print"
dc('ralph',X)? Yes(1)
  X='howard'
dc('bob','bob')? No
dc(X,Y)? Yes(1)
  X='ralph', Y='howard'
";
}
if($testfile eq "testfiles/proj4e4"){
print"
people('joe','jim')? Yes(1)
people(who,'bob')? Yes(3)
  who='bob'
  who='jim'
  who='joe'
people('joe',anyone)? Yes(2)
  anyone='bob'
  anyone='jim'
people(X,X)? Yes(1)
  X='bob'
people(X,Y)? Yes(4)
  X='bob', Y='bob'
  X='jim', Y='bob'
  X='joe', Y='bob'
  X='joe', Y='jim'
employer('ralph',X)? Yes(1)
  X='howard'
employer('bob','bob')? No
employer(X,Y)? Yes(1)
  X='ralph', Y='howard'
";
}
if($testfilre eq "testfiles/proj4e5"){
print"
Schemes populated after 2 passes through the Rules.
snap('67890','Van Pelt','34 Pear','555-5678')? Yes(1)
snap(S,N,A,P)? Yes(2)
  S='12345', N='Snoopy', A='12 Apple', P='555-1234'
  S='67890', N='Van Pelt', A='34 Pear', P='555-5678'
NameHasID('Snoopy',Id)? Yes(1)
  Id='12345'
NameHasID(Name,'67890')? Yes(1)
  Name='Van Pelt'
";
}
if($testfilre eq "testfiles/proj4e6"){
print"
Schemes populated after 2 passes through the Rules.
g('4',B)? Yes(1)
  B='5'
r(E,'3')? Yes(1)
  E='4'
f(A,B)? Yes(2)
  A='1', B='2'
  A='4', B='3'
g(A,B)? Yes(2)
  A='3', B='2'
  A='4', B='5'
r(A,B)? Yes(3)
  A='1', B='2'
  A='3', B='5'
  A='4', B='3'
";
}
if($testfilre eq "testfiles/proj4e7"){
print"
Schemes populated after 2 passes through the Rules.
DeaUoo(A,B,C,D,E)? Yes(3)
  A='a', B='a', C='a', D='a', E='a'
  A='a', B='a', C='b', D='a', E='a'
  A='b', B='a', C='a', D='a', E='a'
DeaUoo(A,B,'a',D,E)? Yes(2)
  A='a', B='a', D='a', E='a'
  A='b', B='a', D='a', E='a'
DeaVoo(A,B,'a',D,E)? No
DeaUoo(A,B,'b',D,E)? Yes(1)
  A='a', B='a', D='a', E='a'
DeaWoo(A,B,'a',D,Applestrudle)? Yes(4)
  A='a', B='a', D='a', Applestrudle='a'
  A='a', B='a', D='a', Applestrudle='b'
  A='a', B='b', D='a', Applestrudle='b'
  A='a', B='b', D='b', Applestrudle='a'
DeaWoo(A,B,'a',D,E)? Yes(4)
  A='a', B='a', D='a', E='a'
  A='a', B='a', D='a', E='b'
  A='a', B='b', D='a', E='b'
  A='a', B='b', D='b', E='a'
DeaWoo('a','a','a','a','b')? Yes(1)
";
}
if($testfilre eq "testfiles/proj4e8"){
print"
Schemes populated after 6 passes through the Rules.
Symmetric(Q,R)? Yes(18)
  Q='1', R='2'
  Q='10', R='9'
  Q='2', R='1'
  Q='2', R='3'
  Q='3', R='2'
  Q='3', R='4'
  Q='4', R='3'
  Q='4', R='5'
  Q='5', R='4'
  Q='5', R='6'
  Q='6', R='5'
  Q='6', R='7'
  Q='7', R='6'
  Q='7', R='8'
  Q='8', R='7'
  Q='8', R='9'
  Q='9', R='10'
  Q='9', R='8'
Reflexive(Q,R)? Yes(9)
  Q='1', R='1'
  Q='2', R='2'
  Q='3', R='3'
  Q='4', R='4'
  Q='5', R='5'
  Q='6', R='6'
  Q='7', R='7'
  Q='8', R='8'
  Q='9', R='9'
Transitive('1',P)? Yes(9)
  P='10'
  P='2'
  P='3'
  P='4'
  P='5'
  P='6'
  P='7'
  P='8'
  P='9'
A('1','2')? Yes(1)
Symmetric('2','1')? Yes(1)
SymTran(X,Y)? Yes(100)
  X='1', Y='1'
  X='1', Y='10'
  X='1', Y='2'
  X='1', Y='3'
  X='1', Y='4'
  X='1', Y='5'
  X='1', Y='6'
  X='1', Y='7'
  X='1', Y='8'
  X='1', Y='9'
  X='10', Y='1'
  X='10', Y='10'
  X='10', Y='2'
  X='10', Y='3'
  X='10', Y='4'
  X='10', Y='5'
  X='10', Y='6'
  X='10', Y='7'
  X='10', Y='8'
  X='10', Y='9'
  X='2', Y='1'
  X='2', Y='10'
  X='2', Y='2'
  X='2', Y='3'
  X='2', Y='4'
  X='2', Y='5'
  X='2', Y='6'
  X='2', Y='7'
  X='2', Y='8'
  X='2', Y='9'
  X='3', Y='1'
  X='3', Y='10'
  X='3', Y='2'
  X='3', Y='3'
  X='3', Y='4'
  X='3', Y='5'
  X='3', Y='6'
  X='3', Y='7'
  X='3', Y='8'
  X='3', Y='9'
  X='4', Y='1'
  X='4', Y='10'
  X='4', Y='2'
  X='4', Y='3'
  X='4', Y='4'
  X='4', Y='5'
  X='4', Y='6'
  X='4', Y='7'
  X='4', Y='8'
  X='4', Y='9'
  X='5', Y='1'
  X='5', Y='10'
  X='5', Y='2'
  X='5', Y='3'
  X='5', Y='4'
  X='5', Y='5'
  X='5', Y='6'
  X='5', Y='7'
  X='5', Y='8'
  X='5', Y='9'
  X='6', Y='1'
  X='6', Y='10'
  X='6', Y='2'
  X='6', Y='3'
  X='6', Y='4'
  X='6', Y='5'
  X='6', Y='6'
  X='6', Y='7'
  X='6', Y='8'
  X='6', Y='9'
  X='7', Y='1'
  X='7', Y='10'
  X='7', Y='2'
  X='7', Y='3'
  X='7', Y='4'
  X='7', Y='5'
  X='7', Y='6'
  X='7', Y='7'
  X='7', Y='8'
  X='7', Y='9'
  X='8', Y='1'
  X='8', Y='10'
  X='8', Y='2'
  X='8', Y='3'
  X='8', Y='4'
  X='8', Y='5'
  X='8', Y='6'
  X='8', Y='7'
  X='8', Y='8'
  X='8', Y='9'
  X='9', Y='1'
  X='9', Y='10'
  X='9', Y='2'
  X='9', Y='3'
  X='9', Y='4'
  X='9', Y='5'
  X='9', Y='6'
  X='9', Y='7'
  X='9', Y='8'
  X='9', Y='9'
";
}
if($testfilre eq "testfiles/proj4e9"){
print"
We need to compute what the output of this file would be
";
}
